export default function Footer() {
    return (
        <footer className="text-center text-lg-start mt-auto">
            <div className="text-center text-muted mt-5" >
                © 2026 Copyright: Jade Brady Fortune Rentals 
                (Images generated by Microsoft Copilot)
            </div>
        </footer>
    );
}